version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: pms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: python_db
      MYSQL_USER: vuanh
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"